### ISSUE TITLE
How does versioning works ?

### ISSUE THREAD

**Issue by lucifer-crybaby** [h5p/h5p-interactive-book#101]
Hi,
How does versions works ? 
I mean in this repo the version of all branches are on same [1.4.2](https://github.com/h5p/h5p-interactive-book/releases/tag/1.4.2)
But in my moodle site it's on 1.3.5 
![image](https://user-images.githubusercontent.com/66128532/168990282-3f635e40-9c14-4d00-ae13-10cf5e8731fc.png)
there is a button(I assume it's for update) but it's greyed out and i can't update interactive book.
Any idea how to bump it to latest version ?

**Comment by otacke** [comment]
That's simply because the version that you find here may not have been released yet.

**Comment by lucifer-crybaby** [comment]
How and where can i know that ? at least release schedule or something like that ? it will be greatly appreciated.

**Comment by otacke** [comment]
I dont' think that the H5P core team has an exact release schedule. You'll notice that an update of a content type is available in the H5P Hub within the list of content types.

The H5P core team provides a list of releases at https://h5p.org/post-hub-releases if you want to check what the latest version is or when some update was released.

**Comment by lucifer-crybaby** [comment]
Oh I see, appreciate it.
